### PR TITLE
Release 0.0.8

### PR DESCRIPTION
**Pull request by raphjaph**
@tcharding @apoelstra I want to make a new release for this crate since it now supports the latest `rust-bitcoin` version.

Some questions on process:

1. For releases and PRs is there a minimum amount of approvals I need before merging?
2. Shall I always just tag you guys or are there other people that can approve as well?
3. Do you want to put this crate in the [Other Crates](https://github.com/rust-bitcoin#other-crates) section on the org homepage?

### CODE REVIEW

**Comment by tcharding** [comment]
> For releases and PRs is there a minimum amount of approvals I need before merging?

Its your crate man, you can have any merge and release policy you want.

> Shall I always just tag you guys or are there other people that can approve as well?

You don't need to tag us (well me anyway), I'm not anymore important than anyone else round here.

> Do you want to put this crate in the [Other Crates](https://github.com/rust-bitcoin#other-crates) section on the org homepage?

This I can definitely do for you!

**Comment by tcharding** [comment]
Hey @raphjaph the `repository` line in the manifest needs updating to point to `rust-bitcoin` org

```
repository = "https://github.com/raphjaph/bip322"
```

**Comment by tcharding** [comment]
https://github.com/rust-bitcoin/.github/pull/3

**Comment by raphjaph** [comment]
Awesome, thanks!

**Pull request merged**
